openapi: 3.1.0
x-stoplight:
  id: kvqiu93nloyq3
info:
  title: grading-api
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  '/grades/{pupil-id}':
    get:
      summary: Get grades for a pupil
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      format: uuid
                      readOnly: true
                    subjectName:
                      type: string
                    grade:
                      type: string
      operationId: get-grades
      description: ''
    post:
      summary: Set grade for a pupil on a subject
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                    readOnly: true
                  subjectName:
                    type: string
                  grade:
                    type: string
      operationId: post-grades
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                subjectName:
                  type: string
                grade:
                  type: string
    parameters:
      - schema:
          type: string
        name: pupil-id
        in: path
        required: true
components:
  schemas:
    User:
      title: User
      type: object
      description: ''
      examples:
        - id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          format: email
        dateOfBirth:
          type: string
          format: date
          example: '1997-10-31'
        emailVerified:
          type: boolean
          description: Set to true if the user's email has been verified.
        createDate:
          type: string
          format: date
          description: The date that the user was created.
      required:
        - id
        - firstName
        - lastName
        - email
        - emailVerified
